# Generated by Django 3.0.8 on 2020-07-10 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('firstName', models.CharField(default='null', max_length=255)),
                ('lastName', models.CharField(default='null', max_length=255)),
                ('address', models.CharField(default='null', max_length=255)),
                ('dob', models.DateField()),
                ('company', models.CharField(default='null', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='null', max_length=255)),
                ('lastName', models.CharField(default='null', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(default='null', max_length=255)),
                ('mobile', models.CharField(default='null', max_length=10)),
                ('address', models.CharField(default='null', max_length=255)),
                ('dob', models.DateField()),
                ('company', models.CharField(default='null', max_length=128)),
                ('city', models.CharField(default='null', max_length=30)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
