# Generated by Django 3.0.8 on 2020-07-10 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterModelTable(
            name='manager',
            table='Manager',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Manager')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
